# Modelling spatio-temporal processes

## 1. Course overview

### 1.1 Literature

* C. Chatfield, The analysis of time series: an introduction. Chapman and Hall: chapters 1, 2 and 3 
* Applied Spatial Data Analysis with R, by R. Bivand, E. Pebesma and V. Gomez-Rubio (Springer; http://www.springer.com/978-0-387-78170-9 ): 
 * Ch 1, 2, 3
 * Ch 4, 5, 6 (whatever is convenient from it)
 * Ch 8 (geostatistics)

### 1.2 Organization

Teachers:
 * Christoph Stasch (exercises)
 * Edzer Pebesma (lectures)

### 1.3 examen:
 * multiple choice, 4 possibilities, 40 questions, 20 need to be correct.

## 2. Where we come from

+ introduction to geostatistics
+ mathematics, linear algebra
+ computer science

### 2.1 geostatistics

+ types of variables: nominal, ordinal, interval, ratio
+ ... discrete, continuous
+ t-tests, ANOVA
+ regression, multiple regression (but now how we compute it)
+ assumption was: observations are independent
+ what does independence mean?

### 2.2 In this course
+ we will study dependence in observations, in 
 + space
 + time
 + or space-time
+ we will study how we can represent phenomena, by
 + mathematical representations (models)
 + computer representations (models)
+ we will consider how well these models correspond to our observations
 

```{r}
sin(3)
```
